# language: c
#
# install:
#   - sudo apt-get install mono-devel mono-gmcs nunit-console
#
# script:
#   - xbuild /p:Configuration=Debug src/PlanktonMono.sln
#   - nunit-console bin/Debug/PlanktonTests.dll

language: csharp
# env:
#   global:
#   - ARTIFACTS_KEY=AKIAIJ6RNS2NO5AJFEWA
#   - secure: "BjS6rHI567Xea+fiTrK6d8NPRlkaY1AK177f6Fi58Inm850Al9i3DCaBLZjVB8oNmVa/KpHv32jM3nebIS5csB7CRDXTlhoX/cHJvTDUWugFQ8zTW+h9pNAOIPHa5FUdmC/szRDNazKB3/cDeKXxETW+QyBgsYpfjJ2MfgZcNDQ="
#   - ARTIFACTS_BUCKET=erdos
#   - ARTIFACTS_S3_REGION=eu-west-1
#   - ARTIFACTS_PERMISSIONS=public-read
#   - ARTIFACTS_TARGET_PATHS=builds
solution: src/Plankton.sln
install:
- nuget restore src/Plankton.sln
- nuget install Grasshopper -source https://pyget.herokuapp.com/
- cp RhinoCommon.*/lib/* lib/
- cp Grasshopper.*/lib/* lib/
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release src/Plankton.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Debug/PlanktonTests.dll
after_success:
- mkdir dist
- zip dist/plankton-${TRAVIS_BUILD_NUMBER}.zip LICENSE.txt README.md
- zip -j dist/plankton-${TRAVIS_BUILD_NUMBER}.zip bin/Release/Plankton.dll bin/Release/Plankton.gha
# - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
# - artifacts upload plankton-${TRAVIS_BUILD_NUMBER}.zip
deploy:
- provider: s3
  access_key_id: AKIAIJ6RNS2NO5AJFEWA
  secret_access_key:
    secure: IoQ9+WncyXz73Q5kp8psmUjSu2ZlxVEOdpoVevbADrXMUIVsgWhzZPzYiBlEvmxYP0S3/hGHN7QT6DbVCZWfZfPsO6Ys39Sg8kvIDg0t54t7jUFFHW1Yw83nrlU1BRk4nfFPkSruhW0vnojLxbOeQPpVQz8SW77NlZF8zlaQvgA=
  bucket: erdos
  skip_cleanup: true
  region: eu-west-1
  local_dir: dist
  upload-dir: builds
  acl: public_read
  on:
    all_branches: true
